---
deployment:
  name: "devbox"

jobs:
  install:
    - nats_server
    - router
    - stager
    - ccdb
    - cloud_controller:
        builtin_services:
          - mysql
          - redis
          - vblob
          - filesystem
          - neo4j
    - health_manager
    - dea
    - uaa
    - uaadb
    - redis_node:
        index: "0"
    - mysql_node:
        index: "0"
    - vblob_node:
        index: "0"
    - neo4j_node:
        index: "0"
    - redis_gateway
    - mysql_gateway
    - vblob_gateway
    - filesystem_gateway
    - neo4j_gateway
